"""
Room and Environment Node factories for synthetic school building generation.

This module implements the "参数化生成逻辑" (parametric generation logic) described
in task.md §5 Phase 1: simulating Rhino/Grasshopper logic to randomly generate
school room nodes with area, aspect ratio constraints, and environmental nodes.

Key classes:
    RoomSpec      — Immutable room type specification (loaded from YAML catalog)
    RoomNode      — Concrete room instance with assigned attributes
    EnvironmentalNode — Virtual global environment node
    RoomCatalog   — Loads and indexes room_catalog.yaml
    RoomFactory   — Generates RoomNode instances with randomized valid attributes
    EnvNodeFactory — Generates EnvironmentalNode instances
"""

from __future__ import annotations

import os
import math
from dataclasses import dataclass, field
from typing import Tuple, List, Dict, Optional
from pathlib import Path

import numpy as np

# Lazy imports to avoid circularity at module level
try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

from utils.enums import (
    RoomType,
    EnvNodeType,
    DaylightLevel,
    NoiseLevel,
    ZoneType,
    ROOM_TO_ZONE,
)


# ============================================================================
# RoomSpec — Immutable room type specification
# ============================================================================

@dataclass(frozen=True)
class RoomSpec:
    """
    Immutable specification for a room type, loaded from room_catalog.yaml.

    Each RoomSpec defines valid parameter ranges and building-code-derived
    defaults for one room type (e.g., classroom, music_room).

    Attributes:
        room_type: Enum value identifying the room type.
        display_name: Chinese name for reporting.
        area_range_sqm: (min, max) expected floor area in m².
        aspect_ratio_range: (min, max) width:depth ratio.
        daylight_level: Daylight requirement intensity.
        noise_level: Noise emission level.
        noise_tolerance: Maximum noise level this room can tolerate nearby.
        occupancy_density: m² per person (GB50099-2011).
        fire_exits_min: Minimum physical connection edges required.
        floor_preference: List of preferred floor numbers (0 = ground).
    """
    room_type: RoomType
    display_name: str
    area_range_sqm: Tuple[float, float]
    aspect_ratio_range: Tuple[float, float]
    daylight_level: DaylightLevel
    noise_level: NoiseLevel
    noise_tolerance: NoiseLevel
    occupancy_density: float
    fire_exits_min: int
    floor_preference: List[int]

    def compute_occupancy(self, area: float) -> int:
        """
        Derived parameter (§4 前置规则富化, 面积推断人数).

        Reference: GB50099-2011 §5.2.1
            Classroom: 1.0 - 1.5 m²/person

        Formula:
            occupancy = max(1, floor(area / occupancy_density))
        """
        return max(1, int(math.floor(area / self.occupancy_density)))

    def requires_daylight(self) -> bool:
        """
        Returns True if this room type has a HIGH daylight requirement.

        Used for:
          - Sight-line edge creation (TopologyRuleEngine)
          - Daylight compliance checking (ConstraintValidator)
        """
        return self.daylight_level >= DaylightLevel.HIGH

    @classmethod
    def from_yaml_entry(cls, room_type: RoomType, entry: dict) -> 'RoomSpec':
        """Factory method: construct RoomSpec from a YAML config entry."""
        return cls(
            room_type=room_type,
            display_name=entry.get('display_name', room_type.value),
            area_range_sqm=tuple(entry['area_range_sqm']),
            aspect_ratio_range=tuple(entry['aspect_ratio_range']),
            daylight_level=DaylightLevel[entry['daylight_level']],
            noise_level=NoiseLevel[entry['noise_level']],
            noise_tolerance=NoiseLevel[entry['noise_tolerance']],
            occupancy_density=float(entry['occupancy_density']),
            fire_exits_min=int(entry['fire_exits_min']),
            floor_preference=list(entry['floor_preference']),
        )


# ============================================================================
# RoomNode — Concrete room instance
# ============================================================================

@dataclass
class RoomNode:
    """
    A concrete room instance with randomly assigned valid attributes.

    Each RoomNode is generated by RoomFactory and represents one spatial unit
    in the school building graph. With standard floors (Phase 1.5), a single
    RoomNode can represent rooms across a range of identical physical floors.

    Attributes:
        room_id: Unique identifier string (e.g., "classroom_03_T1").
        spec: Reference to the immutable RoomSpec.
        area: Concrete assigned floor area in m².
        aspect_ratio: Concrete assigned width:depth ratio.
        floor: Legacy floor number (0 = ground). Set to floor_range[0].
        floor_range: (min_floor, max_floor) inclusive tuple. e.g., (1, 3)
                     means this room template exists on floors 1, 2, 3.
        typical_floor: Standard floor type label ('ground', 'teaching', 'top').
        centroid: (x, y) position within the site (meters).
        zone_id: Functional zone assignment index.
    """
    room_id: str
    spec: RoomSpec
    area: float
    aspect_ratio: float
    floor: int                              # Legacy: floor_range[0]
    floor_range: Tuple[int, int]            # (min_floor, max_floor) inclusive
    typical_floor: str                      # 'ground' | 'teaching' | 'top'
    centroid: Tuple[float, float]
    zone_id: int

    @property
    def num_floors_spanned(self) -> int:
        """Number of physical floors this node represents."""
        return self.floor_range[1] - self.floor_range[0] + 1

    def overlaps_floor(self, other: 'RoomNode') -> bool:
        """Check if two rooms' floor ranges overlap (share at least one floor)."""
        lo = max(self.floor_range[0], other.floor_range[0])
        hi = min(self.floor_range[1], other.floor_range[1])
        return lo <= hi

    # --- Derived properties -------------------------------------------------
    @property
    def occupancy(self) -> int:
        """Estimated number of occupants (derived from area, per §4)."""
        return self.spec.compute_occupancy(self.area)

    @property
    def fire_exits_min(self) -> int:
        """Minimum required fire exits (delegated from spec)."""
        return self.spec.fire_exits_min

    @property
    def room_type(self) -> RoomType:
        """Room type enum (delegated from spec)."""
        return self.spec.room_type

    @property
    def daylight_level(self) -> DaylightLevel:
        """Daylight requirement (delegated from spec)."""
        return self.spec.daylight_level

    @property
    def noise_level(self) -> NoiseLevel:
        """Noise emission level (delegated from spec)."""
        return self.spec.noise_level

    @property
    def noise_tolerance(self) -> NoiseLevel:
        """Noise tolerance (delegated from spec)."""
        return self.spec.noise_tolerance

    @property
    def requires_daylight(self) -> bool:
        """Whether this room needs daylight connection."""
        return self.spec.requires_daylight()

    def euclidean_distance_to(self, other: 'RoomNode') -> float:
        """Compute 2D Euclidean distance to another room (ignoring floor)."""
        dx = self.centroid[0] - other.centroid[0]
        dy = self.centroid[1] - other.centroid[1]
        return math.sqrt(dx * dx + dy * dy)

    def same_floor(self, other: 'RoomNode') -> bool:
        """Check if two rooms share at least one physical floor (floor_range overlap)."""
        return self.overlaps_floor(other)

    def __hash__(self) -> int:
        return hash(self.room_id)

    def __eq__(self, other) -> bool:
        if not isinstance(other, RoomNode):
            return False
        return self.room_id == other.room_id


# ============================================================================
# EnvironmentalNode — Virtual global environment node
# ============================================================================

@dataclass
class EnvironmentalNode:
    """
    Virtual global node representing environmental context (§3.1 环境节点).

    These nodes are NOT physical rooms — they impose macroscopic orientation
    and contextual constraints on the graph.

    Attributes:
        env_id: Unique identifier string (e.g., "south_facing_01").
        env_type: Type of environmental node.
        position: (x, y) position on the site (meters).
        attributes: Type-specific attributes dictionary.
    """
    env_id: str
    env_type: EnvNodeType
    position: Tuple[float, float]
    attributes: Dict[str, float] = field(default_factory=dict)

    def __hash__(self) -> int:
        return hash(self.env_id)

    def __eq__(self, other) -> bool:
        if not isinstance(other, EnvironmentalNode):
            return False
        return self.env_id == other.env_id


# ============================================================================
# RoomCatalog — YAML config loader
# ============================================================================

class RoomCatalog:
    """
    Loads and indexes the room_catalog.yaml configuration.

    Provides O(1) lookup of RoomSpec by RoomType.

    Usage:
        catalog = RoomCatalog.from_yaml('src/config/room_catalog.yaml')
        spec = catalog.get(RoomType.CLASSROOM)
    """

    def __init__(self, specs: Dict[RoomType, RoomSpec]):
        self._specs: Dict[RoomType, RoomSpec] = specs

    @classmethod
    def from_yaml(cls, yaml_path: str) -> 'RoomCatalog':
        """
        Load room specifications from a YAML file.

        Args:
            yaml_path: Path to room_catalog.yaml.

        Returns:
            RoomCatalog instance.

        Raises:
            ImportError: If pyyaml is not installed.
            KeyError: If a required room type is missing from the YAML.
        """
        if not HAS_YAML:
            raise ImportError(
                "pyyaml is required to load YAML configs. "
                "Install with: pip install pyyaml"
            )

        with open(yaml_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)

        room_types = config.get('room_types', {})
        specs: Dict[RoomType, RoomSpec] = {}

        for type_name, entry in room_types.items():
            try:
                room_type = RoomType(type_name)
            except ValueError:
                raise KeyError(
                    f"Unknown room type '{type_name}' in YAML config. "
                    f"Valid types: {[rt.value for rt in RoomType]}"
                )
            specs[room_type] = RoomSpec.from_yaml_entry(room_type, entry)

        # Verify every RoomType is defined in the catalog
        missing = set(RoomType) - set(specs.keys())
        if missing:
            raise KeyError(
                f"Missing room type definitions in catalog: "
                f"{[m.value for m in missing]}"
            )

        return cls(specs)

    def get(self, room_type: RoomType) -> RoomSpec:
        """Get the RoomSpec for a given RoomType."""
        if room_type not in self._specs:
            raise KeyError(f"RoomType {room_type} not found in catalog")
        return self._specs[room_type]

    def list_types(self) -> List[RoomType]:
        """Return all registered room types."""
        return list(self._specs.keys())

    def __contains__(self, room_type: RoomType) -> bool:
        return room_type in self._specs

    def __len__(self) -> int:
        return len(self._specs)


# ============================================================================
# RoomFactory — Random room node generator
# ============================================================================

class RoomFactory:
    """
    Generates RoomNode instances with randomized valid attributes.

    Each call to generate() produces a RoomNode whose area and aspect_ratio
    are uniformly sampled from the RoomSpec's valid ranges — simulating
    parametric design variation in Rhino/Grasshopper.

    Usage:
        catalog = RoomCatalog.from_yaml(...)
        rng = np.random.default_rng(42)
        factory = RoomFactory(catalog, rng)
        room = factory.generate(RoomType.CLASSROOM, floor=2, zone_id=0)
    """

    def __init__(self, catalog: RoomCatalog, rng: Optional[np.random.Generator] = None):
        self._catalog = catalog
        self._rng = rng if rng is not None else np.random.default_rng()
        self._counters: Dict[RoomType, int] = {}

    def generate(
        self,
        room_type: RoomType,
        floor: int = 0,
        zone_id: int = 0,
        centroid: Optional[Tuple[float, float]] = None,
        floor_range: Optional[Tuple[int, int]] = None,
        typical_floor: str = 'ground',
    ) -> RoomNode:
        """
        Generate a single RoomNode with randomized valid attributes.

        Args:
            room_type: Type of room to generate.
            floor: Floor number (0 = ground). Used as fallback if floor_range not set.
            zone_id: Index of the functional zone this room belongs to.
            centroid: Optional (x, y) position. If None, assigned later.
            floor_range: (min_floor, max_floor) for standard floors. If None,
                         defaults to (floor, floor).
            typical_floor: Standard floor type label. Default 'ground'.

        Returns:
            A RoomNode instance with concrete, valid attributes.
        """
        spec = self._catalog.get(room_type)

        # Randomly sample area from valid range
        area_min, area_max = spec.area_range_sqm
        area = float(self._rng.uniform(area_min, area_max))

        # Randomly sample aspect ratio from valid range
        ar_min, ar_max = spec.aspect_ratio_range
        aspect_ratio = float(self._rng.uniform(ar_min, ar_max))

        if floor_range is None:
            floor_range = (floor, floor)

        # Increment counter for unique ID (use typical floor in id)
        count = self._counters.get(room_type, 0)
        self._counters[room_type] = count + 1
        tf_abbr = {'ground': 'G', 'teaching': 'T', 'top': 'P'}.get(typical_floor, 'X')
        room_id = f"{room_type.value}_{count:03d}_{tf_abbr}{floor_range[0]}"

        if centroid is None:
            centroid = (0.0, 0.0)

        return RoomNode(
            room_id=room_id,
            spec=spec,
            area=area,
            aspect_ratio=aspect_ratio,
            floor=floor_range[0],  # legacy floor = first floor in range
            floor_range=floor_range,
            typical_floor=typical_floor,
            centroid=centroid,
            zone_id=zone_id,
        )

    def generate_batch(
        self,
        room_type: RoomType,
        count: int,
        floor: int = 0,
        zone_id: int = 0,
        floor_range: Optional[Tuple[int, int]] = None,
        typical_floor: str = 'ground',
    ) -> List[RoomNode]:
        """Generate multiple RoomNodes of the same type."""
        return [
            self.generate(room_type, floor=floor, zone_id=zone_id,
                          floor_range=floor_range, typical_floor=typical_floor)
            for _ in range(count)
        ]

    def reset_counters(self):
        """Reset ID counters (e.g., for a new generation run)."""
        self._counters.clear()


# ============================================================================
# EnvNodeFactory — Environmental node generator
# ============================================================================

class EnvNodeFactory:
    """
    Generates EnvironmentalNode instances at fixed or semi-random positions.

    Environmental nodes represent global constraints:
      - south_facing: placed at the northern edge (south-facing exposure)
      - main_road_access: placed at the site entry side
      - playground: outdoor activity area
      - green_space: landscape/view amenity
    """

    def __init__(
        self,
        site_bounds: Tuple[float, float, float, float],
        rng: Optional[np.random.Generator] = None,
    ):
        """
        Args:
            site_bounds: (min_x, min_y, max_x, max_y) in meters.
            rng: NumPy random generator for reproducibility.
        """
        self.min_x, self.min_y, self.max_x, self.max_y = site_bounds
        self._rng = rng if rng is not None else np.random.default_rng()
        self._counters: Dict[EnvNodeType, int] = {}

    def _next_id(self, env_type: EnvNodeType) -> str:
        count = self._counters.get(env_type, 0)
        self._counters[env_type] = count + 1
        return f"{env_type.value}_{count:02d}"

    def generate_south_facing(self) -> EnvironmentalNode:
        """
        Generate the south-facing environmental node.

        Position: center of the southern edge (max_y, assuming Y+ = south).
        This node acts as the primary daylight source.
        """
        x = (self.min_x + self.max_x) / 2.0
        y = self.max_y  # Southern boundary
        return EnvironmentalNode(
            env_id=self._next_id(EnvNodeType.SOUTH_FACING),
            env_type=EnvNodeType.SOUTH_FACING,
            position=(x, y),
            attributes={'solar_orientation': 1.0},  # perfect south
        )

    def generate_main_road_access(self, road_side: str = "west") -> EnvironmentalNode:
        """
        Generate the main road access node.

        Position: center of the specified road side.
        Road side determines which boundary the access is on.

        Args:
            road_side: 'west', 'east', 'south', or 'north'.
        """
        if road_side == "west":
            pos = (self.min_x, (self.min_y + self.max_y) / 2.0)
        elif road_side == "east":
            pos = (self.max_x, (self.min_y + self.max_y) / 2.0)
        elif road_side == "south":
            pos = ((self.min_x + self.max_x) / 2.0, self.max_y)
        elif road_side == "north":
            pos = ((self.min_x + self.max_x) / 2.0, self.min_y)
        else:
            raise ValueError(f"Invalid road_side: {road_side}")

        return EnvironmentalNode(
            env_id=self._next_id(EnvNodeType.MAIN_ROAD_ACCESS),
            env_type=EnvNodeType.MAIN_ROAD_ACCESS,
            position=pos,
            attributes={'access_type': 1.0},  # 1 = main
        )

    def generate_playground(self) -> EnvironmentalNode:
        """
        Generate a playground environmental node.

        Position: semi-random location within the site, biased toward
        an open area on the east or west side.
        """
        x = self._rng.uniform(self.min_x + 20, self.max_x - 20)
        y = self._rng.uniform(self.min_y + 10, self.max_y * 0.4)
        return EnvironmentalNode(
            env_id=self._next_id(EnvNodeType.PLAYGROUND),
            env_type=EnvNodeType.PLAYGROUND,
            position=(x, y),
            attributes={'area_approx': 2000.0, 'is_outdoor': 1.0},
        )

    def generate_green_space(self) -> EnvironmentalNode:
        """
        Generate a green space environmental node.

        Position: random location near site boundary, for view quality.
        """
        # Place near a random boundary
        side = self._rng.integers(0, 4)
        if side == 0:  # north
            x = self._rng.uniform(self.min_x, self.max_x)
            y = self.min_y + 5.0
        elif side == 1:  # south
            x = self._rng.uniform(self.min_x, self.max_x)
            y = self.max_y - 5.0
        elif side == 2:  # west
            x = self.min_x + 5.0
            y = self._rng.uniform(self.min_y, self.max_y)
        else:  # east
            x = self.max_x - 5.0
            y = self._rng.uniform(self.min_y, self.max_y)

        return EnvironmentalNode(
            env_id=self._next_id(EnvNodeType.GREEN_SPACE),
            env_type=EnvNodeType.GREEN_SPACE,
            position=(x, y),
            attributes={'view_quality': self._rng.uniform(0.5, 1.0)},
        )

    def generate_all(self, school_size: str = "medium") -> List[EnvironmentalNode]:
        """
        Generate the standard set of environmental nodes.

        Args:
            school_size: 'small', 'medium', or 'large'. Determines
                         how many green_space nodes to generate.

        Returns:
            List of EnvironmentalNode instances.
        """
        nodes = [
            self.generate_south_facing(),
            self.generate_main_road_access(),
        ]

        # Playground for medium+ schools
        if school_size in ("medium", "large"):
            nodes.append(self.generate_playground())

        # Green spaces
        num_green = {"small": 1, "medium": 2, "large": 3}.get(school_size, 2)
        for _ in range(num_green):
            nodes.append(self.generate_green_space())

        return nodes
